### ISSUE TITLE
Display information about 'Die Drei Fragezeichen'

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#1]
## Value Proposition

As a User,
I want to have an overview of all episodes of the audio play 'Die Drei Fragezeichen'
so that I am able to look them up.
​

## Description

![Bildschirm­foto 2023-01-19 um 12 39 08](https://user-images.githubusercontent.com/117563487/213433079-c29b1041-a5d4-4319-833c-057a3fe162ee.png)

​

## Acceptance Criteria

- [x] App displays a list of all **currently** existing episodes
- [x] there is a header to know which app you are currently using

## Tasks

- [x] add database as .json file locally into project ([download source](http://dreimetadaten.de/))
- [x] fetch the json via local route
- [x] map over the data and display the title and number of each episode in a list
- [x] add header component with placeholder name

## Complexity

M

**Comment by SaschaRadojkovic** [comment]
i think that looks good to me

**Comment by AstridOttmann** [comment]
Looks good

**Comment by NikRoe** [comment]
Hey Robin, 
this looks like a promising start!

Your wireframe displays a header that you don't mention in your user story.
You should ask yourself: Does this need to be part of the user story? If so, mention it amongst the acceptance criteria

In general: You can write your value proposition shorter, even though it is the famous series Die Drei Fragezeichen ;).
Like:
As a User,
I want to have an overview of all episodes of the audio play 'Die Drei Fragezeichen'
so that I am able to look them up.

You don't need to mention that you want to make yourself familiar with the structure of the database

From reading the User Story I am not quite sure whether you work with local data in a `.json`-format when starting or if you want to fetch your data

**Comment by RobinWitt** [comment]
Edit:
- shorten value proposition
- add header to acceptance criteria
- clarify fetching from local source
