### ISSUE TITLE
Speakerslist on episode page

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#16]
## Value Proposition

As a user, I want to have an overview of each episode's speakers, so I can look their names up.
​

## Description

<img width="367" alt="Bildschirm­foto 2023-01-29 um 00 03 06" src="https://user-images.githubusercontent.com/117563487/215295272-d2205420-1fac-4c34-b7be-3605ebe223fa.png">

​

## Acceptance Criteria

- [x] in the `Episode Details Page` is a list of speakers of this episode
- [x] the list can be toggled with a button, using similar logic to `Folgenbeschreibung` and `Kapitelliste`
      ​
## Tasks

- [x] add another button to the details page that uses similar logic to the one for the tracklist
- [x] get the list of speakers from the resource and display them in a list element, using the same logic as for the tracklist

## Complexity

(S)

**Comment by Long-HaHoang** [comment]
Hi Robin,

you have have a grammar issue in the first criteria.
- You use `on` instead of `in`

You can shorten your second criteria, if you want to.
For example
> - [ ] The list can be toggled with a button, similar to `Folgenbeschreibung` and `Kapitelliste` 

Besides those minor things. The scope and complexity is ok. It's more less the same to other other lists. 👍

**Comment by RobinWitt** [comment]
Fixed it, thanks!
