### ISSUE TITLE
Save userdata (favorite episodes) to database

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#17]
## Value Proposition

As a logged in user, I want my favorite episodes to be saved permanently so that I don't forget them.
​

## Description
- episodes that the user marks as favorites are stored in an online database
- user needs to be logged in
​

## Acceptance Criteria

- [x] each time the user marks an episode as a favorite, the episode number is stored in the favorites list in the MongoDB collection
- [x] each time the user removes an episode from his favorites, the episode number is removed from the favorites from the MongoDB collection
- [x] check if the user is logged in, otherwise, he can't use the favoring function

## Tasks

- [x] create a new collection 'user' in the existing MongoDB that will store episode numbers of favorites (as an array)
- [x] connect the global state that is already implemented for the favoring logic to be synchronized with the MongoDB collection
- [x] implement checking if user is logged in, if not, remove the "favorite" buttons and icons
      ​

## Complexity

M

**Comment by Long-HaHoang** [comment]
Hi Robin, 
I think it's a fine user story.

Furthermore, do you need the `online` part?
You can also differentiate between types of databases. For example `remote`, `local`, `SQL`, and/or `noSQL` databases.
The names of databases can help, too. E.g. `mySQL`, `MongoDB`, `AWS`, `Azure`, `Firebase`, `Postgres`

**Comment by RobinWitt** [comment]
I clarified the database part, keeping the description because I think that part should be understandable for non-coders.
