### ISSUE TITLE
Bookmark last played track in database

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#18]
## Value Proposition

As a user, I want to be able to save the last track I played, so I can continue listening.
​

## Description

Add Element on Homepage as described below

​

## Acceptance Criteria

- [ ] store the last played track in the user profile database
- [ ] on the homepage is a link that opens the last played track via the implemented Spotify Player

## Tasks

- [ ] add a key to the user database collection "last played track" that is updated when playing
- [ ] add a link to the homepage to resume the last played track with the implemented player

## Complexity

L

**Comment by janneserichsen** [comment]
Looks good to me but maybe you can be more specific in your Tasks and describe it more what you are going to do

**Comment by RobinWitt** [comment]
I updated the tasks and acceptance criteria to be more descriptive

**Comment by anotherMichaelMaier** [comment]
Hey Robin, I'm not sure if i understand your proposition right.
If the User uses the bookmark feature while listening, will "only" the episode be bookmarked or a specific time stamp in this episode?
Maybe you can make that a little more clear to me. 

Everything else looks fine to me.

**Comment by RobinWitt** [comment]
Hi Michael, thanks for the feedback. My plan here is if there is a "bookmark note" in the episode (submitted from the single input field), the whole episode is marked as "currently listening/reading". I'm not super happy with that feature but right now I see no other way in implementing that kind of function...
