### ISSUE TITLE
Refactor homepage, add search page

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#19]
## Value Proposition

As a user, 
I want to have only the suggested episodes and the last listened-to episode on the starting page, 
so I can have a quick overview.
​

## Description
<img width="486" alt="Bildschirm­foto 2023-01-29 um 00 54 29" src="https://user-images.githubusercontent.com/117563487/215296473-c04052d6-ef67-4a2b-b033-46229e8e4228.png">

​

## Acceptance Criteria

- [ ] the list of all episodes, including the filter function, is moved to a separate page
- [ ] in the navigation is a button that links to the new page
- [ ] on the homepage is a new area that shows the last listened-to episode
      ​

## Tasks

- [ ] add a new page and move the list of all episodes and the filtering logic there
- [ ] add a button and respective icon to the navigation bar
- [ ] add an area for the last listened-to episode to the homepage
      ​

## Complexity

M

**Comment by magjo21** [comment]
Hi Robin,
Looks good to me.
