### ISSUE TITLE
Details Page (and linking to it)

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#2]
## Value Proposition

As a User
I want to be able to click on each episode in the list
to see more details of that specific episode
​

## Description
![Bildschirm­foto 2023-01-19 um 15 30 10](https://user-images.githubusercontent.com/117563487/213468683-bb921e14-8ef4-4323-a308-bfc357bbbf5d.png)

## Acceptance Criteria

- [x] if an episode is clicked, the user will see a details page for that specific episode
- [x] the details page contains the following information for now: Title, Number, Artwork, Author, Year

## Tasks

- [x] add a new page in the structure of the app, that uses dynamic routing
- [x] dynamic route accepts the key 'episode number' as slug
- [x] information is fetched from local source depending on slug
- [x] information is displayed in different elements on the details page

## Complexity

M-L

**Comment by ThomasF85** [comment]
Nice user story with good complexity and content!

Please specify the acceptance criteria in more detail (which exact information is being shown on the details page).

**Comment by RobinWitt** [comment]
edit:
- specify shown information

**Comment by ThomasF85** [comment]
Looks good!
