### ISSUE TITLE
add Settings Page

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#20]
## Value Proposition

As a user, I want to change different settings, so I can individualize my app
​

## Description
Settings Page with features described below
​

## Acceptance Criteria

- [x] there is a settings page added
- [x] a new button with a representative icon is added to the navigation
- [x] on the settings page, the user can log out, see their Spotify profile name and image
      ​

## Tasks

- [x] add a new page 'Settings Page'
- [x] add a new button with a descriptive icon to the navigation bar, linking to the settings page
- [x] add a display of the Spotify profile name and image
- [x] add a log-out button

## Complexity

S
