### ISSUE TITLE
Login/Logout Page, user profile

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#21]
## Value Proposition

As a user, 
I want to be able to log in and out so that I can access and store my favorite episodes.
​

## Description

![Bildschirm­foto 2023-02-10 um 11 04 51](https://user-images.githubusercontent.com/117563487/218063627-0e72e374-2947-4d11-ab12-c3fe6693ae4c.png)

​

## Acceptance Criteria

- [x] opening the app pushes the user to the landing page
- [x] on the landing page, the user can log in via NextAuth using Spotify as a provider
- [x] refactor the existing user database so that it can store user sub and favorites

## Tasks

- [x] add a landing page
- [x] add a button that shows either login or logout
- [x] add authentication using next-auth.js

## Complexity

XL
