### ISSUE TITLE
Spotify Web Playback SDK Connection

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#26]
## Value Proposition

As a User, 
I want to have a connection to Spotify in the app, 
so that I can listen to the episodes directly.

## Description

​![Image](https://user-images.githubusercontent.com/117563487/218450448-9fe4727d-0a6b-499e-b0dc-08a5892c7b22.png)

## Acceptance Criteria

- [ ] in the episode details page, the user can click a button to play the episode
- [ ] the player module pops up and plays the selected episode
- [ ] buttons for play, pause, skip, previous and close player
      ​

## Tasks

- [ ] implement Spotify Web Playback SDK
- [ ] add component Spotify player controls and Spotify player module
- [ ] handle errors
      ​

## Complexity

XL
