### ISSUE TITLE
Navigation and 'go back' Link

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#3]
## Value Proposition

As a User that finds himself on the details page, 
I want to have the option to go back to the overview of all episodes.
​

## Description
![Bildschirm­foto 2023-01-19 um 16 00 25](https://user-images.githubusercontent.com/117563487/213477376-584a03fe-498d-471c-9adf-17d0f52ebbc2.png)
​

## Acceptance Criteria

- [x] on the details page at the top left is a 'go back' icon that leads the user to the overview of all episodes
- [x] at the bottom of the viewpoint is a navigation bar 
- [x] that navigation bar contains a 'home' icon, that links to an overview of all episodes

## Tasks

- [x] add a link to the details page, routing back to the overview page
- [x] add component 'navigation' and make it available on all pages
- [x] add a link to 'navigation' routing to the overview page with a home icon
      ​

## Complexity

M

**Comment by ThomasF85** [comment]
Well defined and small user story!

I would have given it a complexity of S, but that is totally up to you.
