### ISSUE TITLE
final styling and bugfixing

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#31]
## Value Proposition

**As a** User 
**I want to** have the best and smoothest user experience
**so that** I can enjoy using the app
​

## Description
Change some final styles and fixes
​

## Acceptance Criteria

- [x] improve visibility and user experience further
      ​

## Tasks

- [x] change final styles (e.g. search bar input color)
- [x] style loading screens
      ​

## Complexity

S

**Comment by minatimar** [comment]
lgtm
