### ISSUE TITLE
Details Page: Description and list of tracks

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#4]
## Value Proposition

As a User, I want to have the option to see a description for each episode. But I don't like spoilers!
I also want to have a list of tracks for each episode, so I can look their names up.
​

## Description
(_wireframes intentionally switched to dark mode_)

![Bildschirm­foto 2023-01-19 um 17 52 56](https://user-images.githubusercontent.com/117563487/213510410-caf943f1-5e3c-4a94-9186-e70e3c791c7a.png)

## Acceptance Criteria

- [x] on the details page is a button called 'Folgenbeschreibung'
- [x] the button only appears if a description text is available
- [x] if the button is clicked, the description text can be toggled
- [x] on the details page is a list that shows all track names of the specific episode
- [x] the list only appears if the track names are available

## Information

- both description text and list of track names are part of the .json file we fetched earlier

## Tasks

- [x] check if there is a description text, if yes, append a button to the details page named 'Folgenbeschreibung'
- [x] add a temporary state to determine if the description text should be displayed or not (default: hidden)
- [x] find a solution to hide or display the text
- [x] connect button and state with a function
- [x] check if there are track names for the specific episode and, if yes, map them on the details page and display them in an ordered list

## Complexity

L

**Comment by niklasrammelkamp** [comment]
Great. Maybe a little add-on: What if there is no Tracklist or Description? Do you wanna let the user know about it? Maybe with a short text "Leider keine Tracklist und oder Beschreibung".

**Comment by RobinWitt** [comment]
That's a very good hint, muchas gracias!
