### ISSUE TITLE
Mark episodes as favorite using global state

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#5]
## Value Proposition

As a User, I want to mark and de-mark episodes as favorites, so I can remember the ones I liked.
​
## Description

![Bildschirm­foto 2023-01-19 um 21 22 29](https://user-images.githubusercontent.com/117563487/213551866-47ec4601-3a26-4d52-a129-2d803bfcd299.png)

## Acceptance Criteria

- [ ] on the overview page in the episode list, there is a button to toggle the respective episodes as favorites
- [ ] on the details page, there is a button to toggle the respective episode as a favorite
- [ ] the favorite icons display the current state (unfilled/filled)
- [ ] the favored state needs to be global since we use it on different pages
      ​
## Tasks

- [ ] add a favorite button to the listed episodes on the overview page
- [ ] add a favorite button to the details page
- [ ] use intuitive icons for both favored states
- [ ] implement toggle function to the buttons
- [ ] store the list of favored episodes in a global state for different pages
      ​

## Complexity

XL

**Comment by niklasrammelkamp** [comment]
Nice Story.
I think the complexity is too big may. Also, I don't know if it's necessary to store the liked episodes in local storage. It could lead to weird bugs or something similar and I think in the future you probably wanna store the states in a database. 
But I really like the scope of the story.

**Comment by RobinWitt** [comment]
Thanks for the review!
That is what I was thinking... I am going to cut the local storage, for now, to make this story a bit smaller.
