### ISSUE TITLE
Add Favorite Page & Navigation Indicator

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#6]
## Value Proposition

As a User, I want to have an extra page to see only my favorites.
​

## Description
![Bildschirm­foto 2023-01-20 um 11 12 41](https://user-images.githubusercontent.com/117563487/213670629-f1d0268c-366d-4753-b8dc-fea99455a8f7.png)
​

## Acceptance Criteria

- [x] add a Favorite Page that displays only the favored episodes
- [x] the Items on the Favorite Page are linked to the Details Page, similar to the Overview Page
- [x] the Favorite Page has the function to toggle the Favorites, similar to the Overview Page
- [x] _**if the User de-marks an episode on the Favorite Page, it will be removed from the Favorite List automatically**_
- [ ] ~~the Favorite Page has a return button, similar to the Details Page~~
- [x] in the Navigation, add an icon for the 'Favorite Page'
- [x] Icons in the Navigation should indicate to the User which page they are currently on
      ​

## Tasks

- [x] add a Page 'Favorite'
- [x] map/filter favored episodes into a list on the Favorite Page
- [ ] ~~add a 'return' button to the Favorite Page~~
- [x] for the Favorite Page, use the same navigation logic as on the Overview Page
- [x] **_make sure to refresh the list of favored episodes as soon as there is a change_**
- [x] add a Link to the Favorite Page in the Navigation
- [x] find a solution to indicate in the Navigation which page the User is currently on
      ​

## Complexity

L

**Comment by ThomasF85** [comment]
Hi Robin,

nice story! However I have some comments:
The value proposition should be short and contain no detailed information. " I also want to know which page I am currently on." describes a minor detail which should be described in the ACs or description. "..that is now able to toggle my favorite episodes" is an information about previously implemented features which is unnecessary.

Also please clarify what happens when you "unfavore" an episode on the favorites page. Does the episode disappear from the page instantly?

**Comment by RobinWitt** [comment]
Edit:
- shortened Value Proposition
- clarified refresh of the favorite list

**Comment by RobinWitt** [comment]
Edit 2:
- removed 'return' button -> since the Favorite Page has a button in the Navigation, there is no need for a 'return' button

thanks @niklasrammelkamp
