### ISSUE TITLE
Get Data from MongoDB Cloud

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#7]
## Value Proposition

As a User, I always want to have access to the newest episodes, so I can stay up to date.
​

## Description
- The user gets up-to-date information about episodes from a cloud MongoDB.
_(no visual change)_
​

## Acceptance Criteria

- [x] the data is fetched from a MongoDB via API routing
- [x] error handling and request methods are implemented
- [x] In case the User has to wait for the response or the request fails, they get appropriate messages
      ​

## Tasks

- [x] add API to pages, implement HTTP request methods
- [x] add necessary DB models and 'dbConnect' function
- [x] make sure that error handling is implemented on the according pages (we want to use useSWR to fetch)
- [x] the User has to be informed if the response is loading or the request has failed

## Complexity

L

**Comment by doemser** [comment]
Here you could further explain what you mean by error handling? Are we talking about conditional rendering here? How do you want to implement this?

**Comment by RobinWitt** [comment]
Edit:
- clarify details about error handling and conditional rendering

**Comment by AstridOttmann** [comment]
It's just a small thing:
the last two pullet points in Acceptance Criteria are sounding more like tasks

**Comment by RobinWitt** [comment]
@AstridOttmann  I was aware of that fact while writing it, but I had a hard time finding another wording. I am open to suggestions!

**Comment by AstridOttmann** [comment]
If you still want to change it, here my suggestion: 
(but I think it's not so important, because it becomes clear, what you mean)

- In case the user has to wait for the response or the request failed, an appropriate error-message like"Loading" , "Not found" or "Error" is displayed instead

**Comment by Long-HaHoang** [comment]
I know there is no visual change but can you add more description to the user story.
I mean there is reason why there is a description section. 

A simple sentence is enough.
> The user gets up-to-date information about episodes from an api.

**Comment by RobinWitt** [comment]
Edit:
- update description as suggested

**Comment by Long-HaHoang** [comment]
LGTM
