### ISSUE TITLE
Recommendations on homepage

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#8]
## Value Proposition

As a User, I want to see the most recent Episode and a random Episode on the Homepage, so that I get recommendations on what to listen to.

​

## Description

![Image](https://user-images.githubusercontent.com/117563487/215074015-dae70ee5-3b0a-4dd5-a766-14c92ddfcd8d.png)

## Acceptance Criteria

- [x] on the Overview Page is a highlighted link, leading to the *existing* Details Page of the most recent episode
- [x] on the Overview Page is a highlighted link, leading to a Randomizer Page
- [x] on the Randomizer Page, the User sees only the Artwork of one random Episode and two options
- [x] Option A: User clicks 'confirm symbol' and is led to the *existing* Details Page of the random Episode
- [x] Option B: User clicks 'refresh symbol' and gets a new random Episode
- [x] on the Randomizer Page is a "return" button, as on the *existing* Details Page

## Tasks

- [x] write a function to filter the most recent episode out of the data resource
- [x] link the most recent episode on the Overview Page
- [x] write a function to get a random episode out of the data resource
- [x] create a 'Randomizer Page' that displays 'return', 'confirm', 'refresh' buttons, and the artwork of the random episode
- [x] link the buttons accordingly
- [x] link to the Randomizer Page from the Overview Page
      ​

## Complexity

L

**Comment by AstridOttmann** [comment]
For several minutes now I was trying to find a better solution for your value proposition, but I was not successful :-)

Actually, there are two use-cases for the user, so maybe you should cut your story into 2 smaller pieces: 
- sort (As a user / I want to be able to sort the list of Episodes by publishing date / so that I can easily see which Episode follows each other
- -most recent on top (As a user / I want to see the most recent Episode on the top of the Overview Page, so I can listen to it (or: so I'm always up to date).

**Comment by RobinWitt** [comment]
You are probably right, I was worried about having too much users stories for the first week but I'm gonna split this one up since it makes more sense.

Thanks for the suggestions, very helpful!

**Comment by RobinWitt** [comment]
Edit:
- move 'sort' function into separate User Story
- change Value Proposition

**Comment by SaschaRadojkovic** [comment]
i think this is nice

**Comment by d-opri** [comment]
is the details page part of the US? if not, you can take the links to it out for now and implement once you reach that User Story. or did you already make a Details Page, since you didnt include tasks to create one

**Comment by RobinWitt** [comment]
@d-opri thanks for the feedback, the Details Page does exist already. I will clarify that in the User Story!
