### ISSUE TITLE
Filter all Episodes and jump to top of List

### ISSUE THREAD

**Issue by RobinWitt** [RobinWitt/capstone-project#9]
## Value Proposition

As a User, 
I want to be able to sort and filter episodes and get back to the top of the episode list 
so I can navigate through the App quicker.
​

## Description
<img width="190" alt="Bildschirm­foto 2023-01-28 um 20 15 20" src="https://user-images.githubusercontent.com/117563487/215286793-055f4d8a-5ea0-4f3f-99eb-162c0a2d54a3.png">

## Acceptance Criteria

- [x] the User is able to filter and sort the list of all episodes by clicking on different category buttons
- - [x] starting with the following buttons: 'alt->neu', 'neu->alt', 'Spezialfolge'
- - [x] the button icon indicates the current assortment
- [x] the User is able to click on a 'jump to top' button which brings him to the start of the list
      ​

## Tasks

- [x] add buttons matching the categories mentioned above
- [x] add functions to filter and sort the list of episodes accordingly
- [x] add a 'jump to top' button that appears when the User scrolls beneath the initial viewpoint
      ​

## Complexity

M

**Comment by Long-HaHoang** [comment]
You have some typos in the user story. 
`Episodes`, `List` and `App` should be lowercase. Well, English 🤷‍♂️
Besides that your `Value Proposition` doesn't conform to the user story template. 

The same in `Acceptance Criteria` and `Tasks`. You should start those with capital letter.
I know it's kind of annoying. You can blame coach Mareike and Jörg 🤣

**Comment by RobinWitt** [comment]
Are you serious?
The headlines are written like this in the user story template.
I write the words in upper case since I describe my components, which are proper nouns.
And however, last time I checked this wasn't an English language learning Bootcamp, so take a break and leave me alone.

**Comment by RobinWitt** [comment]
In my opinion, your wording is offensive and impolite (not for the first time and not only with me), so you might want to reflect and work on that before "well, Englishing" me. That would improve your reviews a lot, which are apart from that, already good and helpful.

**Comment by Long-HaHoang** [comment]
Well I will try to reflect on the wordings I use in the future.
About the heading the this how it's in the template.

> ## Value Proposition
> 
> **As a** ... (User, Author, logged in User...)  
> **I want to** ... (describe the goal)  
> **so that** ... (describe the reason)  



As you can see the first part is bold and separated into three sentences.

I my honest opinion, it does make more sense. You can read the `Value Proposition` faster and clearer about what you want to offer with a user story.

**Comment by Long-HaHoang** [comment]
I know it's not a English lesson and I'm sorry if my wordings comes rude. I will reflect on that.
But I think it's valuable critique. If you mix uppercase with lowercase in a English sentence it's difficult to read.

And yes, components are written in uppercase, but you can also highlight them. E.g. `ComponentName`.
Furthermore nouns in English are generally written in lowercase, of course there are always exceptions to the rule.

**Comment by Long-HaHoang** [comment]
You can also indent your second and third criteria, since it's part of your first.

> - [ ]  the User is able to filter and sort the List of all Episodes by clicking on different category buttons
> - - [ ] starting with the following buttons: 'alt->neu', 'neu->alt', 'Spezialfolge'
>- - [ ]  the Button Icon indicates the current assortment

Can you also be more precise with your fourth criteria?
Just to be really dumb here. But what happens if I click the 'jump to top' button. 
This might help you
- [ ] The 'jump to top' button brings the user to the top of site.

**Comment by RobinWitt** [comment]
Thanks for the feedback. The list indent thing is a nice idea, I didn't think about that before. I made the suggested changes. And I'll try to improve my uppercase/lowercase mix-ups.
